# .github/workflows/build.yml
name: Build Release

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include: 
          - os: ubuntu-latest
            artifact_name: sandgame
            platform_name: linux_x64
          - os: windows-latest
            artifact_name: sandgame.exe
            platform_name: windows_x64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install clang pkg-config libx11-dev libasound2-dev libudev-dev
    - name: Set current date as env variable
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build
      run: cargo build --release
    - name: Move assets into release folder
      run: mv ./assets ./target/release/assets
    - name: Zip for release
      uses: montudor/action-zip@v1
      with:
        args: zip --qq -r project-sandbox_${{ matrix.platform_name }}.zip target/release
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: project-sandbox_${{ matrix.platform_name }}.zip
        asset_name: project-sandbox_${{ matrix.platform_name }}.zip
        overwrite: true
        release_name: dev-build_${DATE}
        
