# .github/workflows/build.yml
name: Build Release

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include: 
          - os: ubuntu-latest
            artifact_name: sandgame
            platform_name: linux_64
          - os: windows-latest
            artifact_name: sandgame.exe
            platform_name: windows_64
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: sandgame ${{ matrix.platform }}
        overwrite: true
        
