# .github/workflows/build.yml
name: Build Release

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include: 
          - os: ubuntu-latest
            artifact_name: sandgame
            platform_name: linux_x64
          - os: windows-latest
            artifact_name: sandgame.exe
            platform_name: windows_x64
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install clang pkg-config libx11-dev libasound2-dev libudev-dev
    - name: Set current date as env variable
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.platform }}-${{ matrix.artifact_name }}
        overwrite: true
        release_name: dev-build_${DATE}
        
